podverse/podverse-rn

src/screens/PodcastsScreen.tsx
src/services/auth.ts
src/services/request.ts
src/state/actions/auth.ts

Added query param for token on sign up
Added error parsing on request failure
Corrected isLoggedIn property placement

Fixed login and sign up issues and error parsing

---

App.tsx
android/app/build.gradle
android/app/src/main/java/com/podverse/MainApplication.java
android/build.gradle
android/settings.gradle
ios/podverse.xcodeproj/project.pbxproj
package.json
yarn.lock

Got Podverse to run on the android emulator

Android build settings

---

src/components/ProfileTableCell.tsx
src/components/ProfileTableHeader.tsx
src/resources/DeepLinks.ts
src/screens/EpisodeScreen.tsx
src/screens/PlayerScreen.tsx
src/screens/ProfileScreen.tsx
src/state/actions/player.ts

Misc fixes to the deep linking setup

Deep links

---

src/components/HeaderTitleSelector.tsx
src/lib/extensions/String.ts
src/screens/EditPlaylistScreen.tsx
src/screens/MakeClipScreen.tsx

The PlaylistScreen and its functions are pretty chaotic. Sorry man :/ we can definitely clean this up, but I don't think anyone is seriously using the Playlist feature right now, so I'm thinking it's ok to be messy for now, and if we need to expand the feature later, we can clean it up first.

Add remove playlistItem and remove Save button from Edit Playlist screen

---

functions/index.js

I haven't actually tested this yet because I don't remember how to test Firebase functions :[

Pull the latest stage database from git before initializing the 

---

src/Router.tsx
src/components/PVButtonGroup.tsx
src/resources/Colors.ts
src/screens/SearchScreen.tsx
src/styles.ts

Search only fires with more than 1 characters
"No Results" Label only showing when there are no results
Button redesign updates
https://github.com/podverse/podverse-rn/projects/5#card-51473357

Search only fires with more than 1 character. Button updates

---

src/screens/ScanQRCodeScreen.tsx
src/services/parser.ts
src/services/user.ts

I think this is code we actually want for Podable, that I forgot to make a PR for 😬

Update specialUserInfoForPodcast handling

---

src/components/DownloadTableCell.tsx
src/components/QueueTableCell.tsx
src/resources/i18n/translations/en.json
src/screens/DownloadsScreen.tsx
src/screens/HistoryScreen.tsx
src/screens/MakeClipScreen.tsx
src/screens/QueueScreen.tsx
src/styles.ts

Also updated cells for Downloads, History and Queue

Make clips overlay

---

src/components/NavSearchIcon.tsx
src/components/PVSearchBar.tsx
src/components/PlayerProgressBar.tsx
src/resources/Images.ts
src/screens/HistoryScreen.tsx

Updated search icon
Fixed player progress bar manual sliding visual glitch

Icon updates

---

App.tsx
android/app/build.gradle
ios/podverse.xcodeproj/project.pbxproj
package.json
src/components/PVActionSheet.tsx
src/components/PlayerControls.tsx
src/components/PlayerMoreActionSheet.tsx
src/resources/Player.ts
src/screens/MakeClipScreen.tsx
src/screens/OnboardingScreen.tsx
src/services/player.ts
src/services/playerEvents.ts

Version bumped to 3.0.7
Actionsheets dismiss on ta outside
Backward time jump set to 10 seconds
Version check overlay fix

Minor fixes

---

src/services/player.ts

Official registered @OPAWG user agents can be found here https://raw.githubusercontent.com/opawg/user-agents/master/src/user-agents.json
https://github.com/opawg/user-agents
Related Documentation for react-native-track-player https://react-native-track-player.js.org/documentation/#track-object

Add custom Podverse user-agent header to media player requests

---

src/components/BoostDropdownBanner.tsx
src/components/MediaPlayerCarousel.tsx
src/components/PVTextInput.tsx
src/components/ValueTagInfoView.tsx
src/lib/valueTagHelpers.ts
src/resources/i18n/translations/en.json
src/screens/FundingScreen.tsx
src/screens/SettingsScreen.tsx
src/services/lnpay.ts
src/services/playerEvents.ts
src/state/actions/auth.ts
src/state/actions/valueTag.ts
yarn.lock

This is a mixture of UX updates for the ValueTags and LNPay integration.

Value tags and LNPay continued

---

src/components/ClipTableCell.tsx
src/components/DownloadTableCell.tsx
src/components/EpisodeTableCell.tsx
src/components/QueueTableCell.tsx
src/screens/HistoryScreen.tsx
src/screens/MakeClipScreen.tsx
src/screens/MyLibraryScreen.tsx
src/screens/PodcastScreen.tsx
src/screens/QueueScreen.tsx
src/services/parser.ts
src/services/podcast.ts
src/state/actions/downloads.ts

Auto download update

---

src/components/ErrorBoundary.tsx
src/components/PVFlatList.tsx
src/components/PVSearchBar.tsx
src/components/SwipeRowBack.tsx
src/lib/downloader.ts
src/screens/AuthScreen.tsx
src/screens/EpisodesScreen.tsx
src/screens/PodcastsScreen.tsx
src/state/actions/auth.ts

Fixes #610 
Fixes an issue were a crash would not reset all tab navigations
Updates some UI issues on the swipelist

Bugfixes 061620

---

src/lib/filters.ts

- Fixed bug where some podcasts do not download or play.
- Fixed bug where podcast data was not refreshing in the player when the next episode loads from the Queue.
- Preserve Make Clip info when navigating back and forth to the Make Clip screen.
- Other bug fixes.

Podverse Beta v3.1.3-rc.4

---

README.md
android/app/build.gradle
android/app/src/debug/res/xml/network_security_config.xml
android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml
ios/podverse.xcodeproj/project.pbxproj
package.json
src/lib/filters.ts

- Re-enable Podverse Bitcoin functionality. (This is apparently getting removed from the Beta version of each build when a new release goes live on the App Store and Google Play Store. To prevent this from happening it appears we will have to create a separate app for Beta versions before the next release.)

Podverse Beta v3.1.4-rc.1

---

App.tsx
ios/Podfile.lock
ios/Pods/Manifest.lock
package.json
src/components/MediaPlayerCarouselViewer.tsx
src/components/MiniPlayer.tsx
src/components/PVFlatList.tsx
src/components/PVVideo.tsx
src/components/PlayerClipInfoBar.tsx
src/components/TimeRemainingWidget.tsx
src/lib/navigate.ts
src/resources/ActionSheet.ts
src/resources/Alerts.ts
src/resources/Interfaces.ts
src/screens/AuthScreen.tsx
src/screens/DownloadsScreen.tsx
src/screens/MakeClipScreen.tsx
src/screens/PlayerScreen.tsx
src/screens/PodcastsScreen.tsx
src/screens/QueueScreen.tsx
src/services/playerBackgroundTimer.ts
src/services/tracking.ts
src/services/userNowPlayingItem.ts
src/state/actions/player.ts
src/state/actions/playerVideo.ts
src/state/initialState.ts
yarn.lock

Most warning fixes addressed. Also protected some properties from accessing them when null

Warning fixes

---

android/app/build.gradle
functions/tests/e2e/runTests.js
functions/tests/e2e/tests/episodesScreenFull.js
functions/tests/e2e/tests/fundingPresent.js
functions/tests/e2e/tests/launchApp.js
functions/tests/e2e/tests/loggedInScreensDidLoad.js
functions/tests/e2e/tests/myProfileScreenFull.js
functions/tests/e2e/tests/nonLoggedInMediaPlayer.js
functions/tests/e2e/tests/nonLoggedInScreensDidLoad.js
functions/tests/e2e/tests/playlistsScreenFull.js
functions/tests/e2e/tests/profilesScreenFull.js
functions/tests/e2e/tests/settingsScreenFull.js
functions/tests/e2e/tests/tableSectionSelectors.js
ios/podverse.xcodeproj/project.pbxproj
package.json
src/resources/Emails.ts
src/screens/AddPodcastByRSSScreen.tsx
src/screens/ContactScreen.tsx
src/screens/MoreScreen.tsx
src/screens/SearchScreen.tsx

Removed Podcast Request function
Updated app to 4.2.2
E2E Test updates

Release 4.2.2

---

@types/alltypes.d.ts
App.tsx
src/lib/opmlExport.ts
src/lib/secutity.ts
src/services/auth.ts
src/services/parser.ts
src/state/actions/auth.ts
src/state/actions/lnpay.ts

Added migration for new secure storage library. Replaced all occurrences of old secure storage

---

src/components/PlayerMoreActionSheet.tsx
src/services/auth.ts
src/services/podcast.ts
src/services/tracking.ts
src/state/global.d.ts

Takes care of #1129 
Mark as played manually from the player will also skip to the next queue item.

Mark as played added to player screen more options

---

android/.settings/org.eclipse.buildship.core.prefs
android/app/src/main/java/com/podverse/MainApplication.java

Increase size allowed for sCursorWindowSize on Android to fix AsyncStorage large file size bug

---

src/components/MediaPlayerCarouselChatRoom.tsx
src/components/WebViewStaticHTML.tsx
src/screens/V4VProvidersAlbyLoginScreen.tsx
src/screens/WebPageScreen.tsx

Source of fix: https://github.com/react-native-webview/react-native-webview/issues/1915#issuecomment-808869253

Fix crash on Android when loading WebView #1218

---

src/screens/PodcastsScreen.tsx

Turn auto-download after subscribe on by default

---

src/state/actions/auth.ts

Fix for custom RSS feeds do not load from server on login

---

src/lib/navigate.ts

Prevent Share button from appearing on Podcast and Episode screen for custom RSS feeds

---

src/services/playerAudio.ts

In audio player change iosCategoryMode to spokenAudio

---

src/services/request.ts
src/services/v4v/providers/alby.ts
src/state/actions/v4v/v4v.ts

Fix not refreshing the Alby access_token

---

src/lib/utility.ts
src/screens/EpisodesScreen.tsx
src/screens/PodcastScreen.tsx

Fix episodes scroll crash with custom RSS feeds

---

src/services/player.ts

Force livestreams to play at 1x speed

---

src/screens/StartPodcastFromTimeScreen.tsx

Fix "start podcast from time" selector

---

src/screens/EmailVerificationScreen.tsx

Don't know this works, but logging in is possible once done with the e-mail.
Resending shouldn't be the primary course of action.

Log-in button moved above resend e-mail

---

android/app/src/main/java/com/podverse/MainActivity.java
android/app/src/main/java/com/podverse/PVUnifiedPushModule.java

This prevents some issues where the latest notification will override all others

Make the requestCode on the notification's PendingIntent unique

---

package.json
src/lib/downloader.ts
src/lib/satoshiStream.ts
src/screens/FundingNowPlayingItemScreen.tsx
src/screens/FundingPodcastEpisodeScreen.tsx
src/screens/V4VBoostagramScreen.tsx
src/services/v4v/v4v.ts
src/state/actions/downloads.ts
src/state/actions/v4v/v4v.ts
yarn.lock

Pass guid (Podcast.podcastGuid) along with v4v TLV records

---

src/lib/carplay/PVCarPlay.android.ts
yarn.lock

closes #1977 by force setting each podcast item's contentStyle to CategoryGrid.

fix: android auto content grid style

---

src/screens/PlayerScreen.tsx
src/screens/PodcastsScreen.tsx
src/state/actions/v4v/v4v.ts

Attempted fixes for "boost buttons often not appearing" (refresh v4v provider connection and global state)

---

android/app/build.gradle
ios/podverse.xcodeproj/project.pbxproj
package.json
src/services/podcastIndex.ts
src/services/v4v/providers/alby.ts
src/services/v4v/v4v.ts
yarn.lock

Release v4.15.3-beta.1

---

android/app/build.gradle

adds GIF support for android; simple dependency addition to app/build.gradle.
related: #2146

feat(android): GIF support

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/podverse/NoxAndroidAutoModule.kt
android/app/src/main/java/com/podverse/PodversePackage.java
android/build.gradle
src/lib/downloader.ts
src/screens/SettingsScreenDownloads.tsx

This should fix some of our longest and worst storage issues on Android. Many thanks to @lovegaoshi for their amazing work ❤️
#2117
#1314
#1004

Fix android external download by lovegaoshi

---

src/services/tools.ts

Release v4.16.3-beta.2

---

src/services/playerAudio.ts

Release v4.16.3-beta.3

---

src/services/tools.ts

Release v4.16.3-beta.4
